## Neural Network Practice

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta

data = yf.download(tickers='AMZN', start='2012-03-11', end='2022-07-10', auto_adjust=False)

data.columns = data.columns.droplevel(1)

data.reset_index(inplace=True)

data.columns.name = None

data.to_csv('amzn_data.csv')

AMZN_df = pd.read_csv('amzn_data.csv')

AMZN_df.drop(AMZN_df.columns[0], axis=1, inplace=True)

[*********************100%***********************]  1 of 1 completed

In [9]:
print(AMZN_df['Close'].dtype)

AMZN_df['RSI'] = ta.rsi(AMZN_df['Close'], length = 15)
AMZN_df['EMAF'] = ta.ema(AMZN_df['Close'], length = 20)
AMZN_df['EMAM'] = ta.ema(AMZN_df['Close'], length = 100)
AMZN_df['EMAS'] = ta.ema(AMZN_df['Close'], length = 150)

AMZN_df['Target'] = (AMZN_df['Adj Close'] - AMZN_df['Open']).shift(-1)

AMZN_df['TargetClass'] = np.where(AMZN_df['Target'] > 0, 1, 0)

display(AMZN_df.head(10))

float64

,Date,Adj Close,Close,High,Low,Open,Volume,RSI,EMAF,EMAM,EMAS,Target,TargetClass
0,2012-03-12,9.1695,9.1695,9.2700,9.1100,9.2065,51752000,NaN,NaN,NaN,NaN,0.033500,1
1,2012-03-13,9.2295,9.2295,9.2435,9.0385,9.1960,88116000,NaN,NaN,NaN,NaN,-0.069500,0
2,2012-03-14,9.1130,9.1130,9.2160,9.0570,9.1825,73994000,NaN,NaN,NaN,NaN,0.120501,1
3,2012-03-15,9.2215,9.2215,9.2215,9.0150,9.1010,83202000,NaN,NaN,NaN,NaN,0.088500,1
4,2012-03-16,9.2525,9.2525,9.2840,9.1175,9.1640,98680000,NaN,NaN,NaN,NaN,0.103500,1
5,2012-03-19,9.2760,9.2760,9.3340,9.1500,9.1725,78068000,NaN,NaN,NaN,NaN,0.372499,1
6,2012-03-20,9.6165,9.6165,9.7205,9.1440,9.2440,183308000,NaN,NaN,NaN,NaN,-0.038500,0
7,2012-03-21,9.5865,9.5865,9.7140,9.5630,9.6250,84288000,NaN,NaN,NaN,NaN,0.092999,1
8,2012-03-22,9.6200,9.6200,9.7030,9.5130,9.5270,74792000,NaN,NaN,NaN,NaN,0.151500,1
9,2012-03-23,9.7520,9.7520,9.8100,9.5900,9.6005,119680000,NaN,NaN,NaN,NaN,0.319500,1

In [74]:
data['TargetNextClose'] = (data['Adj Close']).shift(-1)

display(data.head(10))

Price,Adj Close,Close,High,Low,Open,Volume,RSI,EMAF,EMAM,EMAS,Target,TargetClass,TargetNextClose
Ticker,AMZN,AMZN,AMZN,AMZN,AMZN,AMZN,,,,,,,
Date,,,,,,,,,,,,,
2012-03-12,9.1695,9.1695,9.2700,9.1100,9.2065,51752000,None,None,None,None,0.033500,1,9.2295
2012-03-13,9.2295,9.2295,9.2435,9.0385,9.1960,88116000,None,None,None,None,-0.069500,0,9.1130
2012-03-14,9.1130,9.1130,9.2160,9.0570,9.1825,73994000,None,None,None,None,0.120501,1,9.2215
2012-03-15,9.2215,9.2215,9.2215,9.0150,9.1010,83202000,None,None,None,None,0.088500,1,9.2525
2012-03-16,9.2525,9.2525,9.2840,9.1175,9.1640,98680000,None,None,None,None,0.103500,1,9.2760
2012-03-19,9.2760,9.2760,9.3340,9.1500,9.1725,78068000,None,None,None,None,0.372499,1,9.6165
2012-03-20,9.6165,9.6165,9.7205,9.1440,9.2440,183308000,None,None,None,None,-0.038500,0,9.5865
2012-03-21,9.5865,9.5865,9.7140,9.5630,9.6250,84288000,None,None,None,None,0.092999,1,9.6200
2012-03-22,9.6200,9.6200,9.7030,9.5130,9.5270,74792000,None,None,None,None,0.151500,1,9.7520
2012-03-23,9.7520,9.7520,9.8100,9.5900,9.6005,119680000,None,None,None,None,0.319500,1,10.1435

In [ ]:
data.dropna(subset=['TargetNextClose'], inplace = True)
data.reset_index(drop = True, inplace = True)
data.drop(['Volume', 'Close'], axis = 1, inplace = True)

display(data.head(10))

In [44]:
data_set = data.iloc[:, 0:11]
pd.set_option('display.max_columns', None)

data_set.head(5)

Empty DataFrame
Columns: [(Date, ), (Adj Close, AMZN), (High, AMZN), (Low, AMZN), (Open, AMZN), (RSI, ), (EMAF, ), (EMAM, ), (EMAS, ), (Target, ), (TargetClass, )]
Index: []