## Neural Network Practice

In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta

data = yf.download(tickers = 'AMZN', start = '2012-03-11', end = '2022-07-10', auto_adjust=False)
data.head(10)

[*********************100%***********************]  1 of 1 completed

Price      Adj Close   Close    High     Low    Open     Volume
Ticker          AMZN    AMZN    AMZN    AMZN    AMZN       AMZN
Date
2012-03-12    9.1695  9.1695  9.2700  9.1100  9.2065   51752000
2012-03-13    9.2295  9.2295  9.2435  9.0385  9.1960   88116000
2012-03-14    9.1130  9.1130  9.2160  9.0570  9.1825   73994000
2012-03-15    9.2215  9.2215  9.2215  9.0150  9.1010   83202000
2012-03-16    9.2525  9.2525  9.2840  9.1175  9.1640   98680000
2012-03-19    9.2760  9.2760  9.3340  9.1500  9.1725   78068000
2012-03-20    9.6165  9.6165  9.7205  9.1440  9.2440  183308000
2012-03-21    9.5865  9.5865  9.7140  9.5630  9.6250   84288000
2012-03-22    9.6200  9.6200  9.7030  9.5130  9.5270   74792000
2012-03-23    9.7520  9.7520  9.8100  9.5900  9.6005  119680000

In [42]:
data['RSI'] = ta.rsi(data.Close, length = 15)
data['EMAF'] = ta.ema(data.Close, length = 20)
data['EMAM'] = ta.ema(data.Close, length = 100)
data['EMAS'] = ta.ema(data.Close, length = 150)

data['Target'] = (data['Adj Close'] - data['Open']).shift(-1)

data['TargetClass'] = np.where(data['Target'] > 0, 1, 0)

In [43]:
data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace = True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close'], axis = 1, inplace = True)

/var/folders/0w/sth8nzm513v609lmyg7vsnfc0000gn/T/ipykernel_37145/592041747.py:5: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  data.drop(['Volume', 'Close'], axis = 1, inplace = True)

In [44]:
data_set = data.iloc[:, 0:11]
pd.set_option('display.max_columns', None)

data_set.head(5)

Empty DataFrame
Columns: [(Date, ), (Adj Close, AMZN), (High, AMZN), (Low, AMZN), (Open, AMZN), (RSI, ), (EMAF, ), (EMAM, ), (EMAS, ), (Target, ), (TargetClass, )]
Index: []